### ISSUE TITLE
KeyError in plot tests

### ISSUE THREAD

**Issue by bhorowitz** [CosmicFish/CosmicFish#6]
I successfully built cosmicfish (on NERSC's edison system) without any apparent errrors. When doing "make run_test" and "make examples" I get the following error many times for most/all plotting related tests:

Traceback (most recent call last):
  File "/usr/common/usg/python/2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/global/u2/b/bhorowit/CosmicFish/python/cosmicfish_pylib_test/test_fisher_plot.py", line 331, in test_init_plot_multiple_2D
    test_plotter = fp.CosmicFishPlotter( fishers=self.fisher_list_test )
  File "/global/u2/b/bhorowit/CosmicFish/python/cosmicfish_pylib/fisher_plot.py", line 96, in __init__
    self.plot_settings = CosmicFish_PlotSettings()
  File "/global/u2/b/bhorowit/CosmicFish/python/cosmicfish_pylib/fisher_plot_settings.py", line 245, in __init__
    matplotlib.rcParams['axes.labelpad']       = 5.0
  File "/usr/common/software/python/matplotlib/1.4.3/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 869, in __setitem__
    See rcParams.keys() for a list of valid parameters.' % (key,))
KeyError: u'axes.labelpad is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'

Perhaps there is some matplotlib version dependency that isn't listed here: https://github.com/CosmicFish/CosmicFish ?

**Comment by mraveri** [comment]
Hi @bhorowitz , thank you for signaling the odd behavior! This could be related to the matplotlib version. On my laptop I have matplotlib 1.5.1 and it works fine. What version are you using at NERSC?
In the meantime I'll try to see whether that setting is really necessary...

**Comment by bhorowitz** [comment]
Hmmm... Interesting! I have 1.4.3... I'll see if I can try it out with 1.5.1

**Comment by CosmicFish** [comment]
Hi @bhorowitz, the setting 'axes.labelpad' is used to calculate the spacing between objects in plots to tweak the appearance and seems to be contained in a matplotlib update between 1.4.3 and 1.5.1. I put a comment in the readme to signal the compatibility issue as no easy way out comes to my mind. Did you manage to find a way around?
